services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=farm_db
      - POSTGRES_USER=farm
      - POSTGRES_PASSWORD=farm_pw
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - .docker/postgres:/var/lib/postgresql/data:delegated

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@yopmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    restart: always

